"""Emit a C++ header fragment containing the trained model as a static function.

`m2cgen` transpiles a fitted `sklearn` model into a plain C function
`double score(double* input)` (or one returning a vector — see below) that
takes the 6 features and returns per-class scores.

We wrap that into a header that exposes:

    static const char* const SIREN_TAG_CLASS_NAMES[NUM_CLASSES] = { ... };
    static const int   SIREN_TAG_NUM_CLASSES = NUM_CLASSES;
    static const int   SIREN_TAG_MODEL_VERSION = N;

    static void siren_tag_score(const float features_in[NUM_FEATURES],
                                float scores_out[NUM_CLASSES]) {
        double x[NUM_FEATURES];
        for (int i = 0; i < NUM_FEATURES; ++i) x[i] = (double)features_in[i];
        // --- generated body starts here ---
        // m2cgen's score functions, one per class (multi-output case):
        ...
        // --- generated body ends here ---
    }

The C++ runtime then picks the top-3 indices and maps them to class names.
"""
from __future__ import annotations

from pathlib import Path

import m2cgen as m2c

from feature_config import CLASS_NAMES, MODEL_VERSION, NUM_CLASSES, NUM_FEATURES


def emit_cpp(model, out_path: Path) -> None:
    """Write the generated header fragment to `out_path`."""
    # m2cgen supports MultiOutputClassifier via the .estimators_ attribute;
    # we render each per-class classifier as its own score function.
    per_class_code: list[str] = []
    for c in range(NUM_CLASSES):
        estimator = model.estimators_[c]
        code = m2c.export_to_c(estimator, function_name=f"siren_tag_score_class_{c}")
        per_class_code.append(code)

    # Build the wrapper. We mangle the generated bodies into a single
    # `siren_tag_score(float*, float*)` function the runtime calls.
    body_lines: list[str] = []
    body_lines.append("        // Per-class scores from the trained sklearn model.")
    body_lines.append("        // m2cgen-generated; do not edit by hand — re-run scripts/siren-tag-model/run.sh to refresh.")
    body_lines.append("        // Each score function returns a single double; we store into scores_out[c].")
    body_lines.append("        double _x[NUM_FEATURES];")
    body_lines.append("        for (int _i = 0; _i < NUM_FEATURES; ++_i) _x[_i] = (double)features_in[_i];")
    body_lines.append("        (void)_x;")
    body_lines.append("")

    for c in range(NUM_CLASSES):
        # Extract just the function body of the generated C function. The
        # generated code is `static double <name>(double input[...]) { ... }`
        # — we inline the body here and capture its return into a local.
        body_lines.append(f"        {{ // class {c} = {CLASS_NAMES[c]!r}")
        body_lines.append(f"            double _s = siren_tag_score_class_{c}(_x);")
        body_lines.append(f"            scores_out[{c}] = (float)_s;")
        body_lines.append("        }")
        body_lines.append("")

    # Compose the full header file
    parts: list[str] = []
    parts.append("// AUTO-GENERATED by scripts/siren-tag-model/emit_cpp.py via m2cgen.")
    parts.append("// DO NOT EDIT BY HAND — re-run scripts/siren-tag-model/run.sh to refresh.")
    parts.append(f"// Model version: {MODEL_VERSION}")
    parts.append(f"// Classes ({NUM_CLASSES}): {', '.join(CLASS_NAMES)}")
    parts.append(f"// Features ({NUM_FEATURES}): see feature_config.FEATURE_NAMES")
    parts.append("")
    parts.append("#pragma once")
    parts.append("")
    parts.append("#include <cstddef>")
    parts.append("")
    parts.append(f"static const int SIREN_TAG_NUM_FEATURES = {NUM_FEATURES};")
    parts.append(f"static const int SIREN_TAG_NUM_CLASSES  = {NUM_CLASSES};")
    parts.append(f"static const int SIREN_TAG_MODEL_VERSION = {MODEL_VERSION};")
    parts.append("")
    parts.append("static const char* const SIREN_TAG_CLASS_NAMES[SIREN_TAG_NUM_CLASSES] = {")
    for name in CLASS_NAMES:
        parts.append(f'    "{name}",')
    parts.append("};")
    parts.append("")

    # First, the per-class free functions generated by m2cgen. Strip any
    # duplicate `#include` lines and any outer `static` qualifier that would
    # conflict with the wrapper's own storage.
    for c in range(NUM_CLASSES):
        code = per_class_code[c]
        # Drop the leading "static " on the function definition so it has
        # external linkage in the wrapper TU.
        code = code.replace("static double ", "double ")
        parts.append(code.rstrip())
        parts.append("")

    # Then the wrapper function the runtime calls.
    parts.append("// Compute per-class scores. Output is in [0, 1] (sigmoid of forest votes).")
    parts.append("static void siren_tag_score(const float features_in[SIREN_TAG_NUM_FEATURES],")
    parts.append("                           float scores_out[SIREN_TAG_NUM_CLASSES]) {")
    parts.extend(body_lines)
    parts.append("}")

    out_path.write_text("\n".join(parts) + "\n")
