#pragma once
#include <rack.hpp>
#include "SirenDataSource.hpp"
#include "SirenAudio.hpp"

// dr_libs — declarations only (implementations compiled in SirenDrLibs.cpp)
#include "../../../dep/drlibs/dr_wav.h"
#include "../../../dep/drlibs/dr_flac.h"
#include "../../../dep/drlibs/dr_mp3.h"

namespace StoermelderPackOne {
namespace Siren {

static const std::vector<std::string> SUPPORTED_EXTENSIONS = { ".wav", ".WAV", ".flac", ".FLAC", ".mp3", ".MP3" };
inline bool isSupportedAudioFile(const std::string& path) {
	std::string ext = rack::system::getExtension(rack::system::getFilename(path));
	for (const std::string& e : SUPPORTED_EXTENSIONS)
		if (ext == e) return true;
	return false;
}

// Returns "_siren" + 6 unique lowercase letters for generated filenames.
// The fixed "_siren" marker lets isGeneratedFile() identify them for browser filtering.
inline std::string randomFileSuffix() {
	static const char letters[] = "abcdefghijklmnopqrstuvwxyz";
	unsigned long long seed = (unsigned long long)std::time(nullptr);
	seed ^= (unsigned long long)(size_t)&seed;
	std::string s = "_siren";
	s.reserve(12);
	for (int i = 0; i < 6; i++) {
		seed = seed * 6364136223846793005ULL + 1442695040888963407ULL;
		s += letters[(seed >> 33) % 26];
	}
	return s;
}

// Returns true for WAV files generated by Siren (name contains "_siren" + 6 letters before .wav).
inline bool isGeneratedFile(const std::string& filename) {
	// pattern: <stem>_siren<6 lowercase letters>.wav  → fixed tail is 16 chars
	static constexpr size_t TAIL = 16; // 1('_') + 5('siren') + 6(random) + 4('.wav') = 16
	if (filename.size() < TAIL) return false;
	size_t markerPos = filename.size() - TAIL;
	if (filename.compare(markerPos, 6, "_siren") != 0) return false;
	for (size_t i = markerPos + 6; i < filename.size() - 4; i++)
		if (!islower((unsigned char)filename[i])) return false;
	return filename.compare(filename.size() - 4, 4, ".wav") == 0;
}

// ─── format-specific audio I/O (only place dr_libs are used directly) ────────

// Decode header-only metadata (fast; does not decode PCM).
inline bool loadAudioInfo(const std::string& path, AudioInfo& out) {
	std::string ext = rack::system::getExtension(rack::system::getFilename(path));
	for (char& c : ext) c = (char)tolower(c);

	if (ext == ".wav") {
		drwav wav;
		if (!drwav_init_file(&wav, path.c_str(), nullptr)) return false;
		out.sampleRate      = (int)wav.sampleRate;
		out.channels        = (int)wav.channels;
		out.bitDepth        = (int)wav.bitsPerSample;
		out.frameCount      = (int64_t)wav.totalPCMFrameCount;
		out.durationSeconds = wav.sampleRate > 0
		                    ? (float)wav.totalPCMFrameCount / (float)wav.sampleRate : 0.f;
		drwav_uninit(&wav);
		return true;
	}
	if (ext == ".flac") {
		drflac* flac = drflac_open_file(path.c_str(), nullptr);
		if (!flac) return false;
		out.sampleRate      = (int)flac->sampleRate;
		out.channels        = (int)flac->channels;
		out.bitDepth        = (int)flac->bitsPerSample;
		out.frameCount      = (int64_t)flac->totalPCMFrameCount;
		out.durationSeconds = flac->sampleRate > 0
		                    ? (float)flac->totalPCMFrameCount / (float)flac->sampleRate : 0.f;
		drflac_close(flac);
		return true;
	}
	if (ext == ".mp3") {
		drmp3 mp3;
		if (!drmp3_init_file(&mp3, path.c_str(), nullptr)) return false;
		out.sampleRate      = (int)mp3.sampleRate;
		out.channels        = (int)mp3.channels;
		out.bitDepth        = 16;
		out.frameCount      = (int64_t)drmp3_get_pcm_frame_count(&mp3);
		out.durationSeconds = mp3.sampleRate > 0
		                    ? (float)out.frameCount / (float)mp3.sampleRate : 0.f;
		drmp3_uninit(&mp3);
		return true;
	}
	return false;
}

// ─── FileSystemAudioStream ───────────────────────────────────────────────────
// Keeps a dr_libs decoder open so frames are read on demand — no full-file buffer.

struct FileSystemAudioStream : AudioStream {
	enum class Fmt { WAV, FLAC, MP3 } fmt;

	drwav   wav  = {};
	drflac* flac = nullptr;
	drmp3   mp3  = {};

	int     ch = 0, sr = 0;
	int64_t total = 0;

	// Seek table for MP3 — calculated once at open time so every subsequent seek is a
	// binary search + decode of a handful of MP3 frames rather than a full linear scan.
	// Memory is owned here; drmp3 holds a raw pointer via drmp3_bind_seek_table.
	std::vector<drmp3_seek_point> mp3SeekTable;

	~FileSystemAudioStream() override {
		if (fmt == Fmt::WAV)               drwav_uninit(&wav);
		else if (fmt == Fmt::FLAC && flac) drflac_close(flac);
		else if (fmt == Fmt::MP3)          drmp3_uninit(&mp3);
	}

	int     channels()    const override { return ch; }
	int     sampleRate()  const override { return sr; }
	int64_t totalFrames() const override { return total; }

	int64_t readF32(float* buffer, int64_t frameCount) override {
		if (fmt == Fmt::WAV)
			return (int64_t)drwav_read_pcm_frames_f32(&wav, (drwav_uint64)frameCount, buffer);
		if (fmt == Fmt::FLAC)
			return (int64_t)drflac_read_pcm_frames_f32(flac, (drflac_uint64)frameCount, buffer);
		if (fmt == Fmt::MP3)
			return (int64_t)drmp3_read_pcm_frames_f32(&mp3, (drmp3_uint64)frameCount, buffer);
		return 0;
	}

	bool seekTo(int64_t frameIndex) override {
		if (fmt == Fmt::WAV)
			return drwav_seek_to_pcm_frame(&wav, (drwav_uint64)frameIndex) == DRWAV_TRUE;
		if (fmt == Fmt::FLAC)
			return drflac_seek_to_pcm_frame(flac, (drflac_uint64)frameIndex) != 0;
		if (fmt == Fmt::MP3)
			return drmp3_seek_to_pcm_frame(&mp3, (drmp3_uint64)frameIndex) != 0;
		return false;
	}
};

// ─── FileSystemDataSource ─────────────────────────────────────────────────────

struct FileSystemDataSource : DataSource {
	std::string root;
	RootMetadata metadata_;

	explicit FileSystemDataSource(const std::string& rootPath) : root(rootPath) {
		metadata_.rootPath = root;
		metadata_.load(metadataFilePath());
	}

	~FileSystemDataSource() override {
		saveMetadata();
	}

	std::string metadataFilePath() const {
		std::string dir = rack::asset::user("Stoermelder-P1");
		return dir + "/siren-" + hashPath(root) + ".json";
	}

	RootMetadata* getMetadata() override { return &metadata_; }

	void saveMetadata() override {
		if (isTesting()) return;
		rack::system::createDirectories(rack::asset::user("Stoermelder-P1"));
		metadata_.save(metadataFilePath());
	}

	std::string rootPath() const override { return root; }

	std::string getRootDisplayName() const override {
		return rootDisplayName(root);
	}

	static std::string rootDisplayName(const std::string& rootPath) {
		ghc::filesystem::path p(rootPath);
		std::string name = p.filename().string();
		return name.empty() ? p.string() : name;
	}

	std::string resolveAbsPath(const std::string& id) const { return root + id; }

	DataSourceNode resolveNode(const std::string& relativePath) const override {
		DataSourceNode node;
		node.relativePath    = relativePath;
		node.name            = ghc::filesystem::path(relativePath).filename().string();
		node.fullPath        = root + relativePath;
		node.isContainer     = false;
		AudioInfo ai;
		if (::StoermelderPackOne::Siren::loadAudioInfo(node.fullPath, ai))
			node.durationSeconds = ai.durationSeconds;
		return node;
	}


	bool isSupportedFile(const std::string& path) const override {
		return isSupportedAudioFile(path);
	}

	std::vector<DataSourceNode> loadChildrenSync(const std::string& dirPath) override {
		std::vector<DataSourceNode> result;
		ghc::filesystem::path base(root);

		auto scan = [&](const std::string& path) {
			try {
				for (const auto& entry : ghc::filesystem::directory_iterator(path)) {
					DataSourceNode node;
					node.fullPath = entry.path().string();
					node.name = entry.path().filename().string();
					node.isContainer = entry.is_directory();
					// Relative path from root, starting with '/'
					auto rel = entry.path().lexically_relative(base);
					node.relativePath = "/" + rel.generic_string();
					if (node.isContainer || isSupportedAudioFile(node.fullPath)) {
						if (!node.isContainer) {
							if (isGeneratedFile(node.name)) continue;
							AudioInfo ai;
							if (::StoermelderPackOne::Siren::loadAudioInfo(node.fullPath, ai))
								node.durationSeconds = ai.durationSeconds;
						}
						result.push_back(std::move(node));
					}
				}
			}
			catch (...) {}
			std::sort(result.begin(), result.end(), [](const DataSourceNode& a, const DataSourceNode& b) {
				// Containers first, then files; both alphabetical
				if (a.isContainer != b.isContainer) return a.isContainer > b.isContainer;
				return rack::string::lowercase(a.name) < rack::string::lowercase(b.name);
			});
		};
		scan(dirPath.empty() ? root : dirPath);
		return result;
	}

	void loadChildrenAsync(const std::string& path, TaskWorker& worker,
			std::function<void(std::vector<DataSourceNode>)> onDone) override {
		std::string scanPath = path.empty() ? root : path;
		std::string rootCopy = root;
		worker.work([scanPath, rootCopy, onDone]() {
			std::vector<DataSourceNode> result;
			ghc::filesystem::path base(rootCopy);
			try {
				for (const auto& entry : ghc::filesystem::directory_iterator(scanPath)) {
					DataSourceNode node;
					node.fullPath = entry.path().string();
					node.name = entry.path().filename().string();
					node.isContainer = entry.is_directory();
					auto rel = entry.path().lexically_relative(base);
					node.relativePath = "/" + rel.generic_string();
					if (node.isContainer || isSupportedAudioFile(node.fullPath)) {
						if (!node.isContainer) {
							if (isGeneratedFile(node.name)) continue;
							AudioInfo ai;
							if (::StoermelderPackOne::Siren::loadAudioInfo(node.fullPath, ai))
								node.durationSeconds = ai.durationSeconds;
						}
						result.push_back(std::move(node));
					}
				}
			}
			catch (...) {}
			std::sort(result.begin(), result.end(), [](const DataSourceNode& a, const DataSourceNode& b) {
				if (a.isContainer != b.isContainer) return a.isContainer > b.isContainer;
				return rack::string::lowercase(a.name) < rack::string::lowercase(b.name);
			});
			onDone(std::move(result));
		});
	}

	std::string getDisplayName(const std::string& id) const override {
		return rack::system::getFilename(id);
	}

	std::string getRelativePath(const std::string& id) const override {
		return id;
	}

	int64_t getTimestamp(const std::string& id) const override {
		return getFileTimestamp(resolveAbsPath(id));
	}

	bool loadAudioInfo(const std::string& id, AudioInfo& out) const override {
		return ::StoermelderPackOne::Siren::loadAudioInfo(resolveAbsPath(id), out);
	}

	std::unique_ptr<AudioStream> openAudioStream(const std::string& id) const override {
		std::string absPath = resolveAbsPath(id);
		std::string ext = rack::system::getExtension(rack::system::getFilename(absPath));
		for (char& c : ext) c = (char)tolower(c);

		auto s = std::unique_ptr<FileSystemAudioStream>(new FileSystemAudioStream());
		if (ext == ".wav") {
			if (!drwav_init_file(&s->wav, absPath.c_str(), nullptr)) return nullptr;
			s->fmt = FileSystemAudioStream::Fmt::WAV;
			s->ch  = (int)s->wav.channels;
			s->sr  = (int)s->wav.sampleRate;
			s->total = (int64_t)s->wav.totalPCMFrameCount;
		}
		else if (ext == ".flac") {
			s->flac = drflac_open_file(absPath.c_str(), nullptr);
			if (!s->flac) return nullptr;
			s->fmt = FileSystemAudioStream::Fmt::FLAC;
			s->ch  = (int)s->flac->channels;
			s->sr  = (int)s->flac->sampleRate;
			s->total = (int64_t)s->flac->totalPCMFrameCount;
		}
		else if (ext == ".mp3") {
			if (!drmp3_init_file(&s->mp3, absPath.c_str(), nullptr)) return nullptr;
			s->fmt   = FileSystemAudioStream::Fmt::MP3;
			s->ch    = (int)s->mp3.channels;
			s->sr    = (int)s->mp3.sampleRate;
			s->total = (int64_t)drmp3_get_pcm_frame_count(&s->mp3);

			// Build a seek table so random-access seeking is O(log N) rather than O(N).
			// 1024 points covers a 60-minute file with ~3.5-second granularity; worst-case
			// decode after a seek is then a handful of MP3 frames instead of thousands.
			drmp3_uint32 nPoints = 1024;
			s->mp3SeekTable.resize(nPoints);
			if (drmp3_calculate_seek_points(&s->mp3, &nPoints, s->mp3SeekTable.data())) {
				s->mp3SeekTable.resize(nPoints);
				drmp3_bind_seek_table(&s->mp3, nPoints, s->mp3SeekTable.data());
			} 
			else {
				s->mp3SeekTable.clear();
			}
		} 
		else {
			return nullptr;
		}
		return s;
	}

	std::function<std::string()> prepareForDrop(const std::string& id, bool convertToWav,
			int targetSampleRate = 0, float trimIn  = 0.f, float trimOut = 1.f,
			int resampleQuality = 6) override {

		std::string absPath = resolveAbsPath(id);
		std::string ext = rack::system::getExtension(rack::system::getFilename(absPath));
		for (char& c : ext) c = (char)tolower(c);

		bool needConvert  = convertToWav && (ext == ".flac" || ext == ".mp3");
		bool needResample = targetSampleRate > 0;  // caller passes 0 when resample is off
		bool needTrim     = trimIn > 0.f || trimOut < 1.f;

		if (!needConvert && !needResample && !needTrim) return [absPath]() { return absPath; };

		std::string dir   = ghc::filesystem::path(absPath).parent_path().string();
		std::string fname = rack::system::getFilename(absPath);
		size_t dot        = fname.rfind('.');
		std::string stem  = (dot != std::string::npos) ? fname.substr(0, dot) : fname;
		std::string outPath = dir + "/" + stem + randomFileSuffix() + ".wav";

		return [absPath, outPath, targetSampleRate, trimIn, trimOut, resampleQuality]() -> std::string {
			return processAudioForDrop(absPath, outPath, targetSampleRate, trimIn, trimOut, resampleQuality);
		};
	}

	// Trim, decode, and/or resample src into a new WAV file at dstPath.
	// targetSampleRate == 0 keeps the original rate; trimIn/trimOut are normalised [0,1].
	// resampleQuality is the speex quality (0..10) used when resampling is performed.
	static std::string processAudioForDrop(const std::string& srcPath, const std::string& dstPath,
			int targetSampleRate, float trimIn, float trimOut, int resampleQuality = 6) {

		// Read header only to determine trim region without decoding full PCM.
		AudioInfo info;
		if (!::StoermelderPackOne::Siren::loadAudioInfo(srcPath, info)) return srcPath;
		if (info.channels <= 0 || info.sampleRate <= 0 || info.frameCount <= 0) return srcPath;

		int     channels    = info.channels;
		int     srcRate     = info.sampleRate;
		int64_t totalFrames = info.frameCount;

		// Trim: compute the [trimIn, trimOut] region.
		int64_t startFrame = (int64_t)(trimIn  * (float)totalFrames);
		int64_t endFrame   = (int64_t)(trimOut * (float)totalFrames);
		startFrame = std::max((int64_t)0, std::min(startFrame, totalFrames));
		endFrame   = std::max(startFrame, std::min(endFrame,   totalFrames));
		int64_t trimFrames = endFrame - startFrame;
		if (trimFrames <= 0) return srcPath;

		// Decode only the trimmed region by seeking before reading.
		std::string ext = rack::system::getExtension(rack::system::getFilename(srcPath));
		for (char& c : ext) c = (char)tolower(c);

		std::vector<float> samples((size_t)(trimFrames * channels));
		int64_t framesRead = 0;

		if (ext == ".wav") {
			drwav wav;
			if (!drwav_init_file(&wav, srcPath.c_str(), nullptr)) return srcPath;
			drwav_seek_to_pcm_frame(&wav, (drwav_uint64)startFrame);
			framesRead = (int64_t)drwav_read_pcm_frames_f32(&wav, (drwav_uint64)trimFrames, samples.data());
			drwav_uninit(&wav);
		}
		else if (ext == ".flac") {
			drflac* flac = drflac_open_file(srcPath.c_str(), nullptr);
			if (!flac) return srcPath;
			drflac_seek_to_pcm_frame(flac, (drflac_uint64)startFrame);
			framesRead = (int64_t)drflac_read_pcm_frames_f32(flac, (drflac_uint64)trimFrames, samples.data());
			drflac_close(flac);
		}
		else if (ext == ".mp3") {
			drmp3 mp3;
			if (!drmp3_init_file(&mp3, srcPath.c_str(), nullptr)) return srcPath;
			drmp3_seek_to_pcm_frame(&mp3, (drmp3_uint64)startFrame);
			framesRead = (int64_t)drmp3_read_pcm_frames_f32(&mp3, (drmp3_uint64)trimFrames, samples.data());
			drmp3_uninit(&mp3);
		}
		else {
			return srcPath;
		}

		samples.resize((size_t)(framesRead * channels));
		if (framesRead <= 0) return srcPath;

		// Resample: convert to targetSampleRate when it differs from the source rate.
		int outRate = (targetSampleRate > 0 && targetSampleRate != srcRate)
		            ? targetSampleRate : srcRate;
		std::vector<float> resampled;
		const float* outPtr    = samples.data();
		int64_t      outFrames = framesRead;
		if (outRate != srcRate) {
			int64_t outCapacity = (int64_t)((double)framesRead * outRate / srcRate) + 256;
			resampled.resize((size_t)(outCapacity * channels));
			dsp::SampleRateConverter<2> src;
			src.setChannels(std::min(channels, 2));
			src.setRates(srcRate, outRate);
			// Clamp to speex's documented range; out-of-range values would assert / destroy
			// the resampler state silently in refreshState().
			int q = resampleQuality;
			if (q < 0)  q = 0;
			if (q > 10) q = 10;
			src.setQuality(q);
			int inF  = (int)std::min(framesRead,   (int64_t)INT_MAX);
			int outF = (int)std::min(outCapacity,  (int64_t)INT_MAX);
			src.process(outPtr, channels, &inF, resampled.data(), channels, &outF);
			resampled.resize((size_t)outF * channels);
			outPtr    = resampled.data();
			outFrames = (int64_t)outF;
		}

		// Write output WAV.
		drwav_data_format fmt = {};
		fmt.container     = drwav_container_riff;
		fmt.format        = DR_WAVE_FORMAT_IEEE_FLOAT;
		fmt.channels      = (drwav_uint32)channels;
		fmt.sampleRate    = (drwav_uint32)outRate;
		fmt.bitsPerSample = 32;
		drwav wav;
		if (!drwav_init_file_write(&wav, dstPath.c_str(), &fmt, nullptr)) return srcPath;
		drwav_write_pcm_frames(&wav, (drwav_uint64)outFrames, outPtr);
		drwav_uninit(&wav);
		return dstPath;
	}

	void appendNodeMenuItems(ui::Menu* menu, const DataSourceNode& node, std::function<void()> onChanged) override {
		if (node.isContainer) {
			std::string dirPath = node.fullPath;

			menu->addChild(createMenuItem("Show folder", "", [dirPath]() {
				rack::system::openDirectory(dirPath);
			}));

			menu->addChild(new ui::MenuSeparator);

			// Sticky submenu: scan container, then show all tags; clicking adds/removes
			// the tag for every direct audio file in the container.
			menu->addChild(Rack::createStickySubmenuItem("Tag all files", RIGHT_ARROW, [this, dirPath, onChanged](ui::Menu* tagMenu) {
				// Scan for direct audio children (runs on UI thread; acceptable for a menu action)
				auto children = loadChildrenSync(dirPath);
				std::vector<std::string> audioRels;
				for (const auto& child : children)
					if (!child.isContainer)
						audioRels.push_back(child.relativePath);

				if (audioRels.empty()) {
					tagMenu->addChild(createMenuLabel("No audio files in folder"));
					return;
				}

				auto allTagsSet = metadata_.allTags();
				std::vector<std::string> sorted(allTagsSet.begin(), allTagsSet.end());
				std::sort(sorted.begin(), sorted.end());

				for (const std::string& tag : sorted) {
					// Check whether ALL files already carry this tag
					bool allHave = true;
					for (const auto& rel : audioRels) {
						auto fileTags = metadata_.getTags(rel);
						if (std::find(fileTags.begin(), fileTags.end(), tag) == fileTags.end()) {
							allHave = false;
							break;
						}
					}

					struct ContainerTagItem : ui::MenuItem {
						FileSystemDataSource* src;
						std::vector<std::string> rels;
						std::string tag;
						bool wasAllHave;
						std::function<void()> onChanged;
						void onAction(const event::Action& e) override {
							if (wasAllHave)
								for (const auto& rel : rels) src->metadata_.removeTag(rel, tag);
							else
								for (const auto& rel : rels) src->metadata_.addTag(rel, tag);
							src->saveMetadata();
							if (onChanged) onChanged();
						}
					};

					ContainerTagItem* item   = new ContainerTagItem;
					item->text            = tag;
					item->rightText       = CHECKMARK(allHave);
					item->src             = this;
					item->rels            = audioRels;
					item->tag             = tag;
					item->wasAllHave      = allHave;
					item->onChanged       = onChanged;
					tagMenu->addChild(item);
				}
			}));
		}
		else {
			std::string dir = ghc::filesystem::path(node.fullPath).parent_path().string();
			menu->addChild(createMenuItem("Open containing folder", "", [dir]() {
				rack::system::openDirectory(dir);
			}));

			std::string rel = node.relativePath;

			menu->addChild(new ui::MenuSeparator);

			// Favorite toggle
			menu->addChild(createCheckMenuItem("Favorite", "",
				[this, rel]() { return metadata_.isFavorite(rel); },
				[this, rel, onChanged]() {
					metadata_.setFavorite(rel, !metadata_.isFavorite(rel));
					saveMetadata();
					if (onChanged) onChanged();
				}
			));

			menu->addChild(new ui::MenuSeparator);
			menu->addChild(createMenuLabel("Tags"));

			// Text field for adding a new tag
			struct FileNewTagField : ui::TextField {
				RootMetadata* metadata;
				std::string rel;
				FileSystemDataSource* src;
				std::function<void()> onChanged;
				void onSelectKey(const event::SelectKey& e) override {
					if (e.action == GLFW_PRESS && e.key == GLFW_KEY_ENTER) {
						std::string tag = rack::string::trim(text);
						if (!tag.empty()) {
							metadata->addTag(rel, tag);
							src->saveMetadata();
							if (onChanged) onChanged();
						}
						ui::MenuOverlay* overlay = getAncestorOfType<ui::MenuOverlay>();
						if (overlay) overlay->requestDelete();
						e.consume(this);
						return;
					}
					if (!e.getTarget()) ui::TextField::onSelectKey(e);
				}
			};
			FileNewTagField* ntf = new FileNewTagField;
			ntf->box.size.x  = 150.f;
			ntf->placeholder = "New tag...";
			ntf->metadata    = &metadata_;
			ntf->rel         = rel;
			ntf->src         = this;
			ntf->onChanged   = onChanged;
			menu->addChild(ntf);
			APP->event->setSelectedWidget(ntf);

			// All known tags with checkmarks — live toggle per item
			struct FileTagItem : ui::MenuItem {
				RootMetadata* metadata;
				std::string rel;
				std::string tag;
				FileSystemDataSource* src;
				std::function<void()> onChanged;
				void onAction(const event::Action& e) override {
					auto current = metadata->getTags(rel);
					std::string tagLow = rack::string::lowercase(tag);
					bool has = std::any_of(current.begin(), current.end(), [&](const std::string& t) {
						return rack::string::lowercase(t) == tagLow;
					});
					if (has) metadata->removeTag(rel, tag);
					else     metadata->addTag(rel, tag);
					src->saveMetadata();
					if (onChanged) onChanged();
					e.unconsume();
				}
				void step() override {
					auto current = metadata->getTags(rel);
					std::string tagLow = rack::string::lowercase(tag);
					bool has = std::any_of(current.begin(), current.end(), [&](const std::string& t) {
						return rack::string::lowercase(t) == tagLow;
					});
					rightText = CHECKMARK(has);
					MenuItem::step();
				}
			};

			auto allTagsSet = metadata_.allTags();
			std::vector<std::string> sorted(allTagsSet.begin(), allTagsSet.end());
			std::sort(sorted.begin(), sorted.end());
			for (const std::string& tag : sorted) {
				FileTagItem* item = new FileTagItem;
				item->text      = tag;
				item->metadata  = &metadata_;
				item->rel       = rel;
				item->tag       = tag;
				item->src       = this;
				item->onChanged = onChanged;
				menu->addChild(item);
			}
		}
	}
};

} // namespace Siren
} // namespace StoermelderPackOne
