#pragma once
#include <rack.hpp>
#include "SirenDataSource.hpp"
#include "SirenAudio.hpp"
#include <fstream>
#include "../../vcv/fs.hpp"
#include "../../vcv/ui.hpp"

// dr_libs — declarations only (implementations compiled in SirenDrLibs.cpp)
#include "../../../dep/drlibs/dr_wav.h"
#include "../../../dep/drlibs/dr_flac.h"
#include "../../../dep/drlibs/dr_mp3.h"


namespace StoermelderPackOne {
namespace Siren {
namespace filesystem {


inline bool isSupportedAudioFile(const std::string& path) {
	static const std::vector<std::string> SUPPORTED_EXTENSIONS = { ".wav", ".WAV", ".flac", ".FLAC", ".mp3", ".MP3" };
	std::string filename = vcv::fs::getFilename(path);
	if (filename[0] == '.') {
		// Ignore files beginning with dot
		return false;
	}
	std::string ext = vcv::fs::getExtension(filename);
	for (const std::string& e : SUPPORTED_EXTENSIONS) {
		if (ext == e) return true;
	}
	return false;
}

// Returns "_siren_" + 6 unique lowercase letters for generated filenames.
// The fixed "_siren_" marker lets isGeneratedFile() identify them for browser filtering.
inline std::string randomFileSuffix() {
	static const char letters[] = "abcdefghijklmnopqrstuvwxyz";
	// Seed once from a non-deterministic source; advance a per-call counter so
	// repeated calls within the same second produce different suffixes.
	static std::mt19937_64 rng = []() {
		std::random_device rd;
		return std::mt19937_64(rd());
	}();
	static std::atomic<unsigned long long> counter{0};
	unsigned long long seed = rng() ^ counter.fetch_add(1, std::memory_order_relaxed);
	std::string s = "_siren_";
	s.reserve(13);
	for (int i = 0; i < 6; i++) {
		seed = seed * 6364136223846793005ULL + 1442695040888963407ULL;
		s += letters[(seed >> 33) % 26];
	}
	return s;
}

// Returns true for WAV files generated by Siren (name contains "_siren_" + 6 letters before .wav).
inline bool isGeneratedFile(const std::string& filename) {
	// pattern: <stem>_siren_<6 lowercase letters>.wav  → fixed tail is 17 chars
	static constexpr size_t TAIL = 17; // 1('_') + 5('siren') + 1('_') + 6(random) + 4('.wav') = 17
	if (filename.size() < TAIL) return false;
	size_t markerPos = filename.size() - TAIL;
	if (filename.compare(markerPos, 7, "_siren_") != 0) return false;
	for (size_t i = markerPos + 7; i < filename.size() - 4; i++) {
		if (!islower((unsigned char)filename[i])) return false;
	}
	return filename.compare(filename.size() - 4, 4, ".wav") == 0;
}

// Decode header-only metadata (fast; does not decode PCM).
inline bool loadAudioInfo(const std::string& path, AudioInfo& out) {
	std::string ext = vcv::fs::getExtension(vcv::fs::getFilename(path));
	for (char& c : ext) c = (char)tolower(c);

	if (ext == ".wav") {
		drwav wav;
		if (!drwav_init_file(&wav, path.c_str(), nullptr)) return false;
		out.sampleRate = (int)wav.sampleRate;
		out.channels = (int)wav.channels;
		out.bitDepth = (int)wav.bitsPerSample;
		out.frameCount = (int64_t)wav.totalPCMFrameCount;
		out.durationSeconds = wav.sampleRate > 0
		                    ? (float)wav.totalPCMFrameCount / (float)wav.sampleRate : 0.f;
		drwav_uninit(&wav);
		return true;
	}
	if (ext == ".flac") {
		drflac* flac = drflac_open_file(path.c_str(), nullptr);
		if (!flac) return false;
		out.sampleRate = (int)flac->sampleRate;
		out.channels = (int)flac->channels;
		out.bitDepth = (int)flac->bitsPerSample;
		out.frameCount = (int64_t)flac->totalPCMFrameCount;
		out.durationSeconds = flac->sampleRate > 0
		                    ? (float)flac->totalPCMFrameCount / (float)flac->sampleRate : 0.f;
		drflac_close(flac);
		return true;
	}
	if (ext == ".mp3") {
		drmp3 mp3;
		if (!drmp3_init_file(&mp3, path.c_str(), nullptr)) return false;
		out.sampleRate = (int)mp3.sampleRate;
		out.channels = (int)mp3.channels;
		out.bitDepth = 16;
		out.frameCount = (int64_t)drmp3_get_pcm_frame_count(&mp3);
		out.durationSeconds = mp3.sampleRate > 0
		                    ? (float)out.frameCount / (float)mp3.sampleRate : 0.f;
		drmp3_uninit(&mp3);
		return true;
	}
	return false;
}

// FileSystemAudioStream
// Keeps a dr_libs decoder open so frames are read on demand — no full-file buffer.
struct FileSystemAudioStream : AudioStream {
	enum class Fmt { WAV, FLAC, MP3 } fmt;

	drwav wav = {};
	drflac* flac = nullptr;
	drmp3 mp3 = {};

	int ch = 0;
	int sr = 0;
	int64_t total = 0;

	// Seek table for MP3 — calculated once at open time so every subsequent seek is a
	// binary search + decode of a handful of MP3 frames rather than a full linear scan.
	// Memory is owned here; drmp3 holds a raw pointer via drmp3_bind_seek_table.
	std::vector<drmp3_seek_point> mp3SeekTable;

	~FileSystemAudioStream() override {
		if (fmt == Fmt::WAV) drwav_uninit(&wav);
		else if (fmt == Fmt::FLAC && flac) drflac_close(flac);
		else if (fmt == Fmt::MP3) drmp3_uninit(&mp3);
	}

	int channels() const override { return ch; }
	int sampleRate() const override { return sr; }
	int64_t totalFrames() const override { return total; }

	int64_t readF32(float* buffer, int64_t frameCount) override {
		if (fmt == Fmt::WAV) {
			return (int64_t)drwav_read_pcm_frames_f32(&wav, (drwav_uint64)frameCount, buffer);
		}
		if (fmt == Fmt::FLAC) {
			return (int64_t)drflac_read_pcm_frames_f32(flac, (drwav_uint64)frameCount, buffer);
		}
		if (fmt == Fmt::MP3) {
			return (int64_t)drmp3_read_pcm_frames_f32(&mp3, (drmp3_uint64)frameCount, buffer);
		}
		return 0;
	}

	bool seekTo(int64_t frameIndex) override {
		if (fmt == Fmt::WAV) {
			return drwav_seek_to_pcm_frame(&wav, (drwav_uint64)frameIndex) == DRWAV_TRUE;
		}
		if (fmt == Fmt::FLAC) {
			return drflac_seek_to_pcm_frame(flac, (drwav_uint64)frameIndex) != 0;
		}
		if (fmt == Fmt::MP3) {
			return drmp3_seek_to_pcm_frame(&mp3, (drmp3_uint64)frameIndex) != 0;
		}
		return false;
	}
};

// FileSystemDataSource
struct FileSystemDataSource : DataSource {
	std::string root;
	std::unique_ptr<MetadataStore> metadata;

	// The metadata store can be substituted (e.g. in tests, to redirect
	// persistence to a scratch location instead of the user's real settings
	// folder) by passing a different MetadataStore subclass instance here.
	explicit FileSystemDataSource(const std::string& rootPath,
			std::unique_ptr<MetadataStore> store = std::unique_ptr<MetadataStore>(new MetadataStore()))
			: root(rootPath), metadata(std::move(store)) {
		metadata->rootPath = root;
		metadata->load();
	}

	~FileSystemDataSource() override {
		saveMetadata();
	}

	MetadataStore* getMetadata() override { return metadata.get(); }

	void saveMetadata() override {
		metadata->save();
	}

	// Remove every waveform cache file keyed by a relative path in this root's
	// metadata. The metadata itself is intentionally left untouched on disk so
	// re-adding the same root later preserves tags/favorites/BPM.
	void cleanup() override {
		if (metadata->samples.empty()) return;

		for (const auto& pair : metadata->samples) {
			std::string cacheFile = cacheFilePathFor(pair.first);
			vcv::fs::remove(cacheFile);
		}
	}

	std::string rootId() const override {
		return "";
	}

	std::string resolveAbsPath(const std::string& id) const {
		return root + id;
	}

	DataSourceNode resolveNode(const std::string& relativePath) const override {
		DataSourceNode node;
		node.relativePath = relativePath;
		node.name = vcv::fs::getFilename(relativePath);
		node.isContainer = false;
		node.durationSeconds = loadCachedDuration(relativePath, resolveAbsPath(relativePath));
		return node;
	}

	// Returns the duration for relativePath, using cached metadata if it's still valid for the
	// file's current mtime, otherwise reading the audio header and updating the cache for next time.
	float loadCachedDuration(const std::string& relativePath, const std::string& absPath) const {
		int64_t ts = getFileTimestamp(absPath);
		MetadataStore* meta = metadata.get();
		if (meta && meta->hasValidAudioInfo(relativePath, ts)) {
			return meta->samples.at(relativePath).durationSeconds;
		}

		AudioInfo ai;
		if (!filesystem::loadAudioInfo(absPath, ai)) return 0.f;
		if (meta) meta->setAudioInfo(relativePath, ai.durationSeconds, ai.sampleRate, ai.bitDepth, ai.channels, ts);
		return ai.durationSeconds;
	}


	bool isSupportedFile(const std::string& path) const override {
		return isSupportedAudioFile(path);
	}

	std::vector<DataSourceNode> loadChildrenSync(const std::string& id, bool withAudioInfo = true) override {
		std::vector<DataSourceNode> result;
		std::string scanPath = root + id;
		for (const std::string& entryPath : vcv::fs::getEntries(scanPath, 0)) {
			DataSourceNode node;
			node.name = vcv::fs::getFilename(entryPath);
			node.isContainer = vcv::fs::isDirectory(entryPath);
			node.relativePath = entryPath.substr(root.size());
			if (node.isContainer || isSupportedAudioFile(node.name)) {
				if (!node.isContainer) {
					if (isGeneratedFile(node.name)) continue;
					if (withAudioInfo) {
						node.durationSeconds = loadCachedDuration(node.relativePath, resolveAbsPath(node.relativePath));
					}
				}
				result.push_back(std::move(node));
			}
		}
		std::sort(result.begin(), result.end(), [](const DataSourceNode& a, const DataSourceNode& b) {
			if (a.isContainer != b.isContainer) return a.isContainer > b.isContainer;
			return rack::string::lowercase(a.name) < rack::string::lowercase(b.name);
		});
		return result;
	}

	void loadChildrenAsync(const std::string& id, ITaskWorker& worker,
			std::function<void(std::vector<DataSourceNode>)> onDone) override {
		std::string scanPath = root + id;
		std::string rootCopy = root;
		worker.work([this, scanPath, rootCopy, onDone]() {
			std::vector<DataSourceNode> result;
			for (const std::string& entryPath : vcv::fs::getEntries(scanPath, 0)) {
				DataSourceNode node;
				node.name = vcv::fs::getFilename(entryPath);
				node.isContainer = vcv::fs::isDirectory(entryPath);
				node.relativePath = entryPath.substr(rootCopy.size());
				if (node.isContainer || isSupportedAudioFile(node.name)) {
					if (!node.isContainer) {
						if (isGeneratedFile(node.name)) continue;
						node.durationSeconds = loadCachedDuration(node.relativePath, rootCopy + node.relativePath);
					}
					result.push_back(std::move(node));
				}
			}
			std::sort(result.begin(), result.end(), [](const DataSourceNode& a, const DataSourceNode& b) {
				if (a.isContainer != b.isContainer) return a.isContainer > b.isContainer;
				return rack::string::lowercase(a.name) < rack::string::lowercase(b.name);
			});
			onDone(std::move(result));
		});
	}

	std::string getDisplayName(const std::string& id) const override {
		return vcv::fs::getFilename(id);
	}

	std::string getRelativePath(const std::string& id) const override {
		return id;
	}

	int64_t getTimestamp(const std::string& id) const override {
		return getFileTimestamp(resolveAbsPath(id));
	}

	bool loadAudioInfo(const std::string& id, AudioInfo& out) const override {
		return filesystem::loadAudioInfo(resolveAbsPath(id), out);
	}

	std::unique_ptr<AudioStream> openAudioStream(const std::string& id) const override {
		std::string absPath = resolveAbsPath(id);
		std::string ext = vcv::fs::getExtension(vcv::fs::getFilename(absPath));
		for (char& c : ext) c = (char)tolower(c);

		auto s = std::unique_ptr<FileSystemAudioStream>(new FileSystemAudioStream());
		if (ext == ".wav") {
			if (!drwav_init_file(&s->wav, absPath.c_str(), nullptr)) return nullptr;
			s->fmt = FileSystemAudioStream::Fmt::WAV;
			s->ch = (int)s->wav.channels;
			s->sr = (int)s->wav.sampleRate;
			s->total = (int64_t)s->wav.totalPCMFrameCount;
		}
		else if (ext == ".flac") {
			s->flac = drflac_open_file(absPath.c_str(), nullptr);
			if (!s->flac) return nullptr;
			s->fmt = FileSystemAudioStream::Fmt::FLAC;
			s->ch = (int)s->flac->channels;
			s->sr = (int)s->flac->sampleRate;
			s->total = (int64_t)s->flac->totalPCMFrameCount;
		}
		else if (ext == ".mp3") {
			if (!drmp3_init_file(&s->mp3, absPath.c_str(), nullptr)) return nullptr;
			s->fmt = FileSystemAudioStream::Fmt::MP3;
			s->ch = (int)s->mp3.channels;
			s->sr = (int)s->mp3.sampleRate;
			s->total = (int64_t)drmp3_get_pcm_frame_count(&s->mp3);

			// Build a seek table so random-access seeking is O(log N) rather than O(N).
			// 1024 points covers a 60-minute file with ~3.5-second granularity; worst-case
			// decode after a seek is then a handful of MP3 frames instead of thousands.
			drmp3_uint32 nPoints = 1024;
			s->mp3SeekTable.resize(nPoints);
			if (drmp3_calculate_seek_points(&s->mp3, &nPoints, s->mp3SeekTable.data())) {
				s->mp3SeekTable.resize(nPoints);
				drmp3_bind_seek_table(&s->mp3, nPoints, s->mp3SeekTable.data());
			}
			else {
				s->mp3SeekTable.clear();
			}
		}
		else {
			return nullptr;
		}
		return s;
	}

	std::function<std::string()> prepareForDrop(const std::string& id, bool convertToWav,
			int targetSampleRate = 0, float trimIn = 0.f, float trimOut = 1.f,
			int resampleQuality = 6, const std::string& outputDir = "",
			bool loopOnDrop = false, float loopCrossfadeDuration = 8.f,
			float repitchSemitones = 0.f, bool alwaysCopy = false) override {

		std::string absPath = resolveAbsPath(id);
		std::string ext = vcv::fs::getExtension(vcv::fs::getFilename(absPath));
		for (char& c : ext) c = (char)tolower(c);

		bool needConvert = convertToWav && (ext == ".flac" || ext == ".mp3");
		bool needResample = targetSampleRate > 0;  // caller passes 0 when resample is off
		bool needTrim = trimIn > 0.f || trimOut < 1.f;
		bool needRepitch = repitchSemitones != 0.f;

		// alwaysCopy only makes sense when there is somewhere to copy to. The "Same
		// folder as source" target leaves outputDir empty; copying a file on top of
		// itself is pointless, so we treat it as a no-op in that case.
		bool needCopy = alwaysCopy && !outputDir.empty();

		if (!needConvert && !needResample && !needTrim && !loopOnDrop && !needRepitch && !needCopy) return [absPath]() { return absPath; };

		std::string dir = !outputDir.empty() ? outputDir : vcv::fs::getDirectory(absPath);
		std::string fname = vcv::fs::getFilename(absPath);
		size_t dot = fname.rfind('.');
		std::string stem = (dot != std::string::npos) ? fname.substr(0, dot) : fname;
		std::string outPath = dir + "/" + stem + randomFileSuffix() + ".wav";

		return [absPath, outPath, targetSampleRate, trimIn, trimOut, resampleQuality, loopOnDrop, loopCrossfadeDuration, repitchSemitones, needCopy]() -> std::string {
			// Copy-only path: no conversion/transcode is required, so a plain
			// filesystem copy is faster and preserves the original format/bit-depth
			// (a re-encode to WAV would always be 32-bit float and lose metadata).
			if (needCopy && targetSampleRate == 0 && trimIn <= 0.f && trimOut >= 1.f
			        && !loopOnDrop && repitchSemitones == 0.f) {
				return copyFileForDrop(absPath, outPath);
			}
			return processAudioForDrop(absPath, outPath, targetSampleRate, trimIn, trimOut, resampleQuality, loopOnDrop, loopCrossfadeDuration, repitchSemitones);
		};
	}

	// Copies src to dst (binary, no re-encoding) and returns dst on success or
	// src on failure. Used by the alwaysCopy path: keeping the original file
	// intact is faster and avoids the lossy re-encode that processAudioForDrop
	// would otherwise do (WAV float32 regardless of source format).
	static std::string copyFileForDrop(const std::string& srcPath, const std::string& dstPath) {
		// Make sure the destination directory exists; patch storage is created
		// for us, but a user-chosen custom folder might be a brand-new path.
		vcv::fs::createDirectories(vcv::fs::getDirectory(dstPath));
		bool r = vcv::fs::copy(srcPath, dstPath);
		if (!r) return srcPath;
		return dstPath;
	}

	// Trim, decode, resample, and/or loop-process src into a new WAV file at dstPath.
	// targetSampleRate == 0 keeps the original rate; trimIn/trimOut are normalised [0,1].
	// resampleQuality is the speex quality (0..10) used when resampling is performed.
	// loopOnDrop applies rotation+crossfade post-processing to make the sample loop-ready.
	// repitchSemitones shifts the pitch without changing duration (0 = off).
	static std::string processAudioForDrop(const std::string& srcPath, const std::string& dstPath,
			int targetSampleRate, float trimIn, float trimOut, int resampleQuality = 6,
			bool loopOnDrop = false, float loopCrossfadeDuration = 8.f, float repitchSemitones = 0.f) {

		// Read header only to determine trim region without decoding full PCM.
		AudioInfo info;
		if (!filesystem::loadAudioInfo(srcPath, info)) return srcPath;
		if (info.channels <= 0 || info.sampleRate <= 0 || info.frameCount <= 0) return srcPath;

		int channels = info.channels;
		int srcRate = info.sampleRate;
		int64_t totalFrames = info.frameCount;

		// Trim: compute the [trimIn, trimOut] region.
		int64_t startFrame = (int64_t)(trimIn * (float)totalFrames);
		int64_t endFrame = (int64_t)(trimOut * (float)totalFrames);
		startFrame = std::max((int64_t)0, std::min(startFrame, totalFrames));
		endFrame = std::max(startFrame, std::min(endFrame, totalFrames));
		int64_t trimFrames = endFrame - startFrame;
		if (trimFrames <= 0) return srcPath;

		// Decode only the trimmed region by seeking before reading.
		std::string ext = vcv::fs::getExtension(vcv::fs::getFilename(srcPath));
		for (char& c : ext) c = (char)tolower(c);

		std::vector<float> samples((size_t)(trimFrames * channels));
		int64_t framesRead = 0;

		if (ext == ".wav") {
			drwav wav;
			if (!drwav_init_file(&wav, srcPath.c_str(), nullptr)) return srcPath;
			drwav_seek_to_pcm_frame(&wav, (drwav_uint64)startFrame);
			framesRead = (int64_t)drwav_read_pcm_frames_f32(&wav, (drwav_uint64)trimFrames, samples.data());
			drwav_uninit(&wav);
		}
		else if (ext == ".flac") {
			drflac* flac = drflac_open_file(srcPath.c_str(), nullptr);
			if (!flac) return srcPath;
			drflac_seek_to_pcm_frame(flac, (drflac_uint64)startFrame);
			framesRead = (int64_t)drflac_read_pcm_frames_f32(flac, (drflac_uint64)trimFrames, samples.data());
			drflac_close(flac);
		}
		else if (ext == ".mp3") {
			drmp3 mp3;
			if (!drmp3_init_file(&mp3, srcPath.c_str(), nullptr)) return srcPath;
			drmp3_seek_to_pcm_frame(&mp3, (drmp3_uint64)startFrame);
			framesRead = (int64_t)drmp3_read_pcm_frames_f32(&mp3, (drmp3_uint64)trimFrames, samples.data());
			drmp3_uninit(&mp3);
		}
		else {
			return srcPath;
		}

		samples.resize((size_t)(framesRead * channels));
		if (framesRead <= 0) return srcPath;

		// Repitch first: SoundTouch's window/hop time constants are tuned for the
		// source sample rate, and pitch-shifting up can extend the spectrum above
		// the source Nyquist — running SRC afterwards lets it anti-alias correctly.
		// Operates on `samples` in place, so outPtr starts pointing at it.
		if (repitchSemitones != 0.f) {
			::StoermelderPackOne::Siren::applyRepitch(samples, channels, srcRate, repitchSemitones);
			framesRead = (int64_t)(samples.size() / (size_t)channels);
			if (framesRead <= 0) return srcPath;
		}

		// Resample: convert to targetSampleRate when it differs from the source rate.
		int outRate = (targetSampleRate > 0 && targetSampleRate != srcRate)
			? targetSampleRate : srcRate;
		std::vector<float> resampled;
		const float* outPtr = samples.data();
		int64_t outFrames = framesRead;
		if (outRate != srcRate) {
			int64_t outCapacity = (int64_t)((double)framesRead * outRate / srcRate) + 256;
			resampled.resize((size_t)(outCapacity * channels));
			dsp::SampleRateConverter<2> src;
			src.setChannels(std::min(channels, 2));
			src.setRates(srcRate, outRate);
			// Clamp to speex's documented range; out-of-range values would assert / destroy
			// the resampler state silently in refreshState().
			int q = resampleQuality;
			if (q < 0) q = 0;
			if (q > 10) q = 10;
			src.setQuality(q);
			int inF = (int)std::min(framesRead, (int64_t)INT_MAX);
			int outF = (int)std::min(outCapacity, (int64_t)INT_MAX);
			src.process(outPtr, channels, &inF, resampled.data(), channels, &outF);
			resampled.resize((size_t)outF * channels);
			outPtr = resampled.data();
			outFrames = (int64_t)outF;
		}

		// Loop post-processing: rotation + crossfade so the file loops smoothly.
		// Operates on an owned copy of the buffer so outPtr/resampled are replaced.
		if (loopOnDrop) {
			std::vector<float> loopBuf(outPtr, outPtr + (size_t)(outFrames * channels));
			::StoermelderPackOne::Siren::applyLoopCrossfade(loopBuf, channels, outRate, loopCrossfadeDuration);
			resampled = std::move(loopBuf);
			outPtr = resampled.data();
			outFrames = (int64_t)(resampled.size() / (size_t)channels);
			if (outFrames <= 0) return srcPath;
		}

		// Declick the start/end so the exported file doesn't pop.
		// Non-loop: trim to the nearest zero crossing within 5 ms (no waveform
		//   modification); falls back to a short cosine fade if none is found.
		// Loop: leave the buffer untouched. applyLoopCrossfade already placed the
		//   loop seam at two consecutive source frames, so the wrap is continuous in
		//   value and slope on every channel and a gapless player loops it with no
		//   artifact. We deliberately do NOT fade the ends to zero: for steep material
		//   with no quiet zero crossing, that fade only trades the boundary click for
		//   an audible low-frequency "bump" (an amplitude hole) on every player.
		if (!loopOnDrop) {
			if (resampled.empty()) {
				resampled.assign(outPtr, outPtr + (size_t)(outFrames * channels));
			}
			::StoermelderPackOne::Siren::applyDeclickZeroCross(resampled, channels, outRate);
			// applyDeclickZeroCross trims to the zero crossings, changing the length;
			// refresh outPtr/outFrames so the write below uses the trimmed buffer.
			outPtr = resampled.data();
			outFrames = (int64_t)(resampled.size() / (size_t)channels);
			if (outFrames <= 0) return srcPath;
		}

		// Write output WAV.
		drwav_data_format fmt = {};
		fmt.container = drwav_container_riff;
		fmt.format = DR_WAVE_FORMAT_IEEE_FLOAT;
		fmt.channels = (drwav_uint32)channels;
		fmt.sampleRate = (drwav_uint32)outRate;
		fmt.bitsPerSample = 32;
		drwav wav;
		if (!drwav_init_file_write(&wav, dstPath.c_str(), &fmt, nullptr)) return srcPath;
		drwav_write_pcm_frames(&wav, (drwav_uint64)outFrames, outPtr);
		drwav_uninit(&wav);
		return dstPath;
	}

	// Adds `tag` to every audio file under `folderId`, recursing into
	// subfolders. Runs on the UI thread; acceptable for a menu action.
	void addTagRecursive(const std::string& folderId, const std::string& tag) {
		for (const auto& child : loadChildrenSync(folderId, false)) {
			if (child.isContainer) {
				addTagRecursive(child.relativePath, tag);
			}
			else {
				getMetadata()->addTag(child.relativePath, tag);
			}
		}
	}

	void appendNodeMenuItems(ui::Menu* menu, const DataSourceNode& node, std::function<void()> onChanged) override {
		// Shared between the new-tag text field and the tag menu items below:
		// the typed text doubles as a live case-insensitive filter on the
		// existing tags while still creating a new tag on enter.
		auto tagFilter = std::make_shared<std::string>();

		auto addNewTagField = [&](std::function<void(const std::string&)> applyTag) {
			struct NewTagField : ui::TextField {
				FileSystemDataSource* src;
				std::function<void()> onChanged;
				std::function<void(const std::string&)> applyTag;
				std::shared_ptr<std::string> filter;
				void onChange(const event::Change& e) override {
					ui::TextField::onChange(e);
					*filter = rack::string::trim(text);
				}
				void onSelectKey(const event::SelectKey& e) override {
					if (e.action == GLFW_PRESS && e.key == GLFW_KEY_ENTER) {
						std::string tag = rack::string::trim(text);
						if (!tag.empty()) {
							applyTag(tag);
							src->saveMetadata();
							if (onChanged) onChanged();
						}
						ui::MenuOverlay* overlay = getAncestorOfType<ui::MenuOverlay>();
						if (overlay) overlay->requestDelete();
						e.consume(this);
						return;
					}
					if (!e.getTarget()) ui::TextField::onSelectKey(e);
				}
			};

			NewTagField* ntf = new NewTagField;
			ntf->box.size.x = 150.f;
			ntf->placeholder = "Filter / new tag...";
			ntf->src = this;
			ntf->onChanged = onChanged;
			ntf->applyTag = applyTag;
			ntf->filter = tagFilter;
			menu->addChild(ntf);
			APP->event->setSelectedWidget(ntf);
		};

		if (node.isContainer) {
			std::string absPath = resolveAbsPath(node.relativePath);
			menu->addChild(createMenuItem("Show folder", "", [absPath]() {
				vcv::fs::openDirectory(absPath);
			}));

			menu->addChild(new ui::MenuSeparator);
			menu->addChild(createMenuLabel("Tags"));
			std::string folderId = node.relativePath;
			addNewTagField([this, folderId](const std::string& tag) {
				addTagRecursive(folderId, tag);
			});

			// Sticky submenu listing all known tags; clicking adds the tag to every
			// audio file under the container (recursively). The container is scanned
			// only when a tag is actually applied, not when the menu is shown — so no
			// checkmarks / toggle state on these items.
			std::string id = node.relativePath;
			menu->addChild(Rack::createStickySubmenuItem("Tag all files", RIGHT_ARROW, [this, id, onChanged, tagFilter](ui::Menu* tagMenu) {
				struct ContainerTagItem : ui::MenuItem {
					FileSystemDataSource* src;
					std::string folderId;
					std::string tag;
					std::function<void()> onChanged;
					std::shared_ptr<std::string> filter;
					void step() override {
						visible = Rack::menuFilterMatches(filter, text);
						MenuItem::step();
					}
					void onAction(const event::Action& e) override {
						src->addTagRecursive(folderId, tag);
						src->saveMetadata();
						if (onChanged) onChanged();
					}
				};

				auto allTagsSet = metadata->allTags();
				std::vector<std::string> sorted(allTagsSet.begin(), allTagsSet.end());
				std::sort(sorted.begin(), sorted.end());
				Rack::addGroupedMenuItems<std::string>(tagMenu, sorted, [this, id, onChanged, tagFilter](const std::string& tag) -> ui::MenuItem* {
					ContainerTagItem* item = new ContainerTagItem;
					item->text = tag;
					item->src = this;
					item->folderId = id;
					item->tag = tag;
					item->onChanged = onChanged;
					item->filter = tagFilter;
					return item;
				}, 16, 16, tagFilter);
			}));
		}
		else {
			std::string dir = vcv::fs::getDirectory(resolveAbsPath(node.relativePath));
			menu->addChild(createMenuItem("Open containing folder", "", [dir]() {
				vcv::fs::openDirectory(dir);
			}));

			menu->addChild(new ui::MenuSeparator);
			std::string rel = node.relativePath;
			menu->addChild(createCheckMenuItem("Favorite", "",
				[this, rel]() { return metadata->isFavorite(rel); },
				[this, rel, onChanged]() {
					metadata->setFavorite(rel, !metadata->isFavorite(rel));
					saveMetadata();
					if (onChanged) onChanged();
				}
			));

			menu->addChild(new ui::MenuSeparator);
			menu->addChild(createMenuLabel("Tags"));
			addNewTagField([this, rel](const std::string& tag) {
				getMetadata()->addTag(rel, tag);
			});

			// All known tags with checkmarks — live toggle per item
			struct FileTagItem : ui::MenuItem {
				std::string rel;
				std::string tag;
				FileSystemDataSource* src;
				std::function<void()> onChanged;
				std::shared_ptr<std::string> filter;
				void onAction(const event::Action& e) override {
					if (has()) src->getMetadata()->removeTag(rel, tag);
					else src->getMetadata()->addTag(rel, tag);
					src->saveMetadata();
					if (onChanged) onChanged();
					e.unconsume();
				}
				void step() override {
					visible = Rack::menuFilterMatches(filter, text);
					rightText = CHECKMARK(has());
					MenuItem::step();
				}
				bool has() {
					auto current = src->getMetadata()->getTags(rel);
					std::string tagLow = rack::string::lowercase(tag);
					bool has = std::any_of(current.begin(), current.end(), [&](const std::string& t) {
						return rack::string::lowercase(t) == tagLow;
					});
					return has;
				}
			};

			auto allTagsSet = metadata->allTags();
			std::vector<std::string> sorted(allTagsSet.begin(), allTagsSet.end());
			std::sort(sorted.begin(), sorted.end());
			Rack::addGroupedMenuItems<std::string>(menu, sorted, [this, rel, onChanged, tagFilter](const std::string& tag) -> ui::MenuItem* {
				FileTagItem* item = new FileTagItem;
				item->text = tag;
				item->rel = rel;
				item->tag = tag;
				item->src = this;
				item->onChanged = onChanged;
				item->filter = tagFilter;
				return item;
			}, 16, 16, tagFilter);
		}
	}
};

// Creates the DataSource implementation appropriate for a RootContainer's
// type. "fs" (the default, and currently the only type) maps to
// FileSystemDataSource.
inline std::shared_ptr<DataSource> createDataSource(const RootContainer& root) {
	return std::make_shared<FileSystemDataSource>(root.path);
}

// Builds the RootContainer for a filesystem path (e.g. picked via an
// "Add root..." folder dialog) — the "fs" type tag is filesystem-specific.
inline RootContainer createRootContainer(const std::string& path) {
	std::string name = vcv::fs::getFilename(path);
	std::string displayName = name.empty() ? path : name;
	return RootContainer(path, "fs", displayName);
}

// Opens a native folder picker and, if the user selects a folder, fills
// `out` with the corresponding RootContainer. Returns false if the dialog
// was cancelled.
inline bool createNewRootContainer(RootContainer& out) {
	std::string path = vcv::ui::openDirectoryDialog();
	if (path.empty()) return false;
	out = createRootContainer(path);
	return true;
}

} // namespace filesystem
} // namespace Siren
} // namespace StoermelderPackOne
