#pragma once
// C++ API wrapper around the auto-generated m2cgen scorer.
//
// The model body (15 per-class scorers + dispatcher, ~41k lines) lives in
// `SirenTagClassifier.hpp` and is regenerated by running
// `bash scripts/siren-tag-model/run.sh`. **Do not hand-edit that file** —
// your changes will be overwritten next time the model retrains.
//
// This header adds the public plugin-side API:
//   - `SuggestedTag`              — (name, score) pair returned to the UI
//   - `TagClassifier::score`      — score a 6-element feature vector
//   - `TagClassifier::topK`       — pick the top-k from a score vector
//   - `TagClassifier::classify`   — feature vector → top-k SuggestedTag list
//   - `TagClassifier::classify`   — AudioStream → top-k SuggestedTag list
//   - `TagClassifier::extractFeatures` — AudioStream → 6-element feature vec
//
// Self-contained: includes the model header (for `siren_tag_score` and the
// class-name table) and `SirenDataSource.hpp` (for `AudioStream`). Does
// NOT include the BPM detector — the STFT scaffold is duplicated locally
// so this header is independent of `SirenBpmDetector.hpp`'s other
// dependencies (jansson, ghc::filesystem, regex).
//
// Feature order (matches `scripts/siren-tag-model/feature_config.py`):
//   [0] spectral_centroid  — mean bin weighted by magnitude, / Nyquist bin
//   [1] spectral_rolloff85 — first bin with cumulative mag ≥ 0.85·total, / Nyquist bin
//   [2] zero_crossing_rate — mean fraction of sign changes per frame
//   [3] rms                — root-mean-square, / 1/√2
//   [4] onset_density      — spectral-flux peaks per second, / 30
//   [5] low_band_ratio     — energy below 250 Hz / total energy

#include "SirenTagClassifier.hpp"   // m2cgen-emitted body + class names
#include "SirenAudioStream.hpp"     // AudioStream interface — no Rack dependency
#include <pffft.h>
#include <algorithm>
#include <cmath>
#include <cstring>
#include <string>
#include <vector>


namespace StoermelderPackOne {
namespace Siren {

struct SuggestedTag {
	std::string name;
	float       score;
};

namespace TagClassifierDetail {

// ── STFT constants — see SirenBpmDetector.hpp:108-115 for rationale ──────
static constexpr int    FFT_SIZE           = 512;
static constexpr int    HOP                = 128;
static constexpr int    HALF_N             = FFT_SIZE / 2;
static constexpr int    TARGET_SR          = 8820;  // doubled for better high-freq coverage

// Normalisation constants — match features.py.
static constexpr float  ONSET_DENSITY_NORM = 30.f;     // peaks/sec → [0, 1]
static constexpr float  LOW_BAND_HZ        = 250.f;    // low_band_ratio cutoff (Hz)
static constexpr float  HIGH_BAND_HZ       = 2000.f;   // high_band_ratio cutoff (Hz)
static constexpr float  MEAN_FLUX_NORM     = 50.f;     // log-flux units/hop → [0, 1]
static constexpr float  RMS_FULL_SCALE     = 0.7071067811865475f; // 1/√2

// ── Helpers (RAII, window, magnitudes, flux, smoothing, peak-pick) ────────

struct PffftSetupGuard {
	PFFFT_Setup* p;
	explicit PffftSetupGuard(int n, pffft_transform_t t) : p(pffft_new_setup(n, t)) {}
	~PffftSetupGuard() { if (p) pffft_destroy_setup(p); }
	PffftSetupGuard(const PffftSetupGuard&) = delete;
	PffftSetupGuard& operator=(const PffftSetupGuard&) = delete;
};

inline void generateHannWindow(float* out, int n) {
	const float denom = (n > 1) ? float(n - 1) : 1.f;
	for (int i = 0; i < n; ++i)
		out[i] = 0.5f * (1.f - std::cos(2.f * float(M_PI) * i / denom));
}

inline void computeMagnitudes(const float* fftOut, float* mag, int halfSize) {
	for (int i = 0; i < halfSize; ++i) {
		float re = fftOut[i * 2];
		float im = fftOut[i * 2 + 1];
		mag[i] = std::sqrt(re * re + im * im);
	}
}

inline float computeSpectralFlux(const float* magCur, const float* magPrev, int numBins) {
	float total = 0.f;
	for (int i = 0; i < numBins; ++i) {
		float cur  = std::max(magCur[i],  1e-6f);
		float prev = std::max(magPrev[i], 1e-6f);
		float diff = std::log(cur) - std::log(prev);
		if (diff > 0.f) total += diff;
	}
	return total;
}

inline void medianFilter3(float* out, const float* in, int n) {
	if (n < 3) {
		if (out != in) std::memcpy(out, in, size_t(n) * sizeof(float));
		return;
	}
	out[0] = in[0];
	for (int i = 1; i < n - 1; ++i) {
		float a = in[i - 1], b = in[i], c = in[i + 1];
		out[i] = std::max(std::min(a, b), std::min(std::max(a, b), c));
	}
	out[n - 1] = in[n - 1];
}

inline void meanSubtract(float* x, int n) {
	if (n <= 0) return;
	double sum = 0.0;
	for (int i = 0; i < n; ++i) sum += x[i];
	float mean = float(sum / double(n));
	for (int i = 0; i < n; ++i) x[i] -= mean;
}

inline int countPeaks(const float* x, int n, float threshold) {
	if (n < 3) return 0;
	int peaks = 0;
	for (int i = 1; i < n - 1; ++i) {
		if (x[i] > threshold && x[i] >= x[i - 1] && x[i] >= x[i + 1]) ++peaks;
	}
	return peaks;
}

} // namespace TagClassifierDetail


// ─── Public API ───────────────────────────────────────────────────────────

struct TagClassifier {
	// Score a feature vector. Clamps the input features to [0, 1]
	// before scoring (the model was trained on clamped features). Writes
	// SIREN_TAG_NUM_CLASSES scores to `out`, also clamped to [0, 1].
	static void score(const float features[SIREN_TAG_NUM_FEATURES], float out[SIREN_TAG_NUM_CLASSES]) {
		float clamped[SIREN_TAG_NUM_FEATURES];
		for (int i = 0; i < SIREN_TAG_NUM_FEATURES; ++i) {
			float v = features[i];
			if (v < 0.f) v = 0.f;
			else if (v > 1.f) v = 1.f;
			clamped[i] = v;
		}
		siren_tag_score(clamped, out);
		for (int i = 0; i < SIREN_TAG_NUM_CLASSES; ++i) {
			float v = out[i];
			if (v < 0.f) v = 0.f;
			else if (v > 1.f) v = 1.f;
			out[i] = v;
		}
	}

	// Pick the top-k indices from a score vector. Returns SuggestedTag
	// pairs sorted by score descending. `k` clamped to [0, NUM_CLASSES].
	static std::vector<SuggestedTag> topK(const float scores[SIREN_TAG_NUM_CLASSES], int k = 3) {
		if (k < 0) k = 0;
		if (k > SIREN_TAG_NUM_CLASSES) k = SIREN_TAG_NUM_CLASSES;

		// Sort all 15 (cheap; saves a heap-based argpartition).
		std::vector<int> idx(SIREN_TAG_NUM_CLASSES);
		for (int i = 0; i < SIREN_TAG_NUM_CLASSES; ++i) idx[i] = i;
		std::sort(idx.begin(), idx.end(), [&](int a, int b) {
			return scores[a] > scores[b];
		});

		std::vector<SuggestedTag> result;
		result.reserve(size_t(k));
		for (int j = 0; j < k; ++j) {
			int c = idx[j];
			result.push_back({ SIREN_TAG_CLASS_NAMES[c], scores[c] });
		}
		return result;
	}

	// Top-k SuggestedTags from a feature vector.
	static std::vector<SuggestedTag> classify(const float features[SIREN_TAG_NUM_FEATURES], int k = 3) {
		float scores[SIREN_TAG_NUM_CLASSES];
		score(features, scores);
		return topK(scores, k);
	}

	// Top-k SuggestedTags straight from an audio stream. Reads the stream
	// once (sequentially). Caps analysis at maxDurationSeconds for speed.
	static std::vector<SuggestedTag> classify(AudioStream& stream, int k = 3,
	                                          float maxDurationSeconds = 30.f) {
		float features[SIREN_TAG_NUM_FEATURES] = {};
		extractFeatures(stream, features, maxDurationSeconds);
		return classify(features, k);
	}

	// Compute the 10 normalized features from an audio stream. The 10
	// features and their order MUST match `feature_config.FEATURE_NAMES`
	// in `scripts/siren-tag-model/feature_config.py` — they are the
	// contract between the C++ runtime and the Python training script.
	// Output is always clamped to [0, 1].
	static void extractFeatures(AudioStream& stream, float out[SIREN_TAG_NUM_FEATURES],
	                            float maxDurationSeconds = 30.f) {
		using namespace TagClassifierDetail;

		for (int i = 0; i < SIREN_TAG_NUM_FEATURES; ++i) out[i] = 0.f;

		int sampleRate = stream.sampleRate();
		int channels   = stream.channels();
		int64_t totalFrames = stream.totalFrames();
		if (totalFrames <= 0 || sampleRate <= 0 || channels <= 0) return;

		// Cap analysis length — features stabilise well before 30 s.
		int64_t maxFrames = int64_t(sampleRate * maxDurationSeconds);
		if (totalFrames > maxFrames) totalFrames = maxFrames;

		// Decimate to ~TARGET_SR. For 44.1/48 kHz inputs this gives a
		// factor of 10/11 — the kept spectrum is well above the kick
		// band (≤ 250 Hz) and well below the SR/2 aliasing bound.
		int decimRate = std::max(1, sampleRate / TARGET_SR);
		int outSR     = sampleRate / decimRate;
		if (outSR <= 0) outSR = TARGET_SR;

		// Read & mix to mono.
		const int64_t BUFSIZE = 65536;
		std::vector<float> mono;
		mono.reserve(size_t(totalFrames / decimRate) + 1024);
		std::vector<float> buf(size_t(BUFSIZE) * size_t(std::max(channels, 1)));
		int64_t framesRead = 0;
		while (framesRead < totalFrames) {
			int64_t toRead = std::min<int64_t>(BUFSIZE, totalFrames - framesRead);
			int64_t got = stream.readF32(buf.data(), toRead);
			if (got <= 0) break;
			for (int64_t f = 0; f < got; f += decimRate) {
				float sum = 0.f;
				int   count = 0;
				for (int ch = 0; ch < channels; ++ch) {
					size_t idx = size_t(f * channels + ch);
					if (idx >= buf.size()) break;
					sum += buf[idx];
					++count;
				}
				if (count > 0) mono.push_back(sum / float(count));
			}
			framesRead += got;
		}
		if (mono.size() < size_t(outSR / 2)) return;  // need at least ~0.5 s

		// ── ZCR per frame, then averaged ─────────────────────────────
		const int zcrFrame = std::max(64, outSR / 33);
		const int zcrNumFrames = int(mono.size()) / zcrFrame;
		float zcrSum = 0.f;
		int   zcrCount = 0;
		for (int f = 0; f < zcrNumFrames; ++f) {
			int startIdx = f * zcrFrame;
			int endIdx   = startIdx + zcrFrame;
			int crossings = 0;
			for (int i = startIdx + 1; i < endIdx; ++i) {
				float a = mono[i - 1];
				float b = mono[i];
				if ((a >= 0.f && b < 0.f) || (a < 0.f && b >= 0.f)) ++crossings;
			}
			zcrSum += float(crossings) / float(zcrFrame);
			++zcrCount;
		}
		float zcrMean = (zcrCount > 0) ? (zcrSum / float(zcrCount)) : 0.f;
		out[2] = zcrMean;

		// ── RMS + peak over the full signal ─────────────────────────────
		double sumSq  = 0.0;
		float  peakAbs = 0.f;
		for (float s : mono) {
			sumSq += double(s) * double(s);
			float a = s < 0.f ? -s : s;
			if (a > peakAbs) peakAbs = a;
		}
		float rms = float(std::sqrt(sumSq / double(mono.size())));
		out[3] = rms / RMS_FULL_SCALE;

		// ── Crest factor (peak / RMS, log-normalised) ─────────────────
		// log(1 + crest) / log(31): sustained sine ~0.2, percussion ~0.7, silence 0.
		{
			float crest = (rms > 1e-6f) ? peakAbs / rms : 0.f;
			out[10] = std::min(1.f, std::log(1.f + crest) / std::log(31.f));
		}

		// ── Harmonic ratio (normalised autocorrelation peak) ──────────
		// Pitch range 49–1100 Hz → lags 8–180 samples at TARGET_SR.
		// Uses first ~0.46 s (4096 samples); periodic → near 1, noise → near 0.
		{
			int n = std::min((int)mono.size(), 4096);
			float r0 = 0.f;
			for (int i = 0; i < n; ++i) r0 += mono[i] * mono[i];
			float maxAC = 0.f;
			if (r0 > 1e-12f) {
				for (int lag = 8; lag <= std::min(180, n - 1); ++lag) {
					float r = 0.f;
					int   cnt = n - lag;
					for (int i = 0; i < cnt; ++i) r += mono[i] * mono[i + lag];
					float rn = r / r0;
					if (rn > maxAC) maxAC = rn;
				}
			}
			out[11] = maxAC;
		}

		// ── STFT (Hann, 4× overlap) ──────────────────────────────────
		int numFrames = int(mono.size());
		int numHops   = (numFrames - FFT_SIZE) / HOP + 1;
		if (numHops < 4) return;

		std::vector<float> window(FFT_SIZE);
		generateHannWindow(window.data(), FFT_SIZE);

		std::vector<float> onsetSignal(numHops, 0.f);
		std::vector<float> magPrev(HALF_N, 0.f);
		std::vector<float> magCur (HALF_N, 0.f);
		std::vector<float> win    (FFT_SIZE, 0.f);
		std::vector<float> spec   (FFT_SIZE, 0.f);
		std::vector<float> work   (FFT_SIZE, 0.f);

		// Per-frame accumulators (squared-magnitude units).
		double centroidBinSum = 0.0;
		double powerSum       = 0.0;
		double powerLow       = 0.0;
		double powerHigh      = 0.0;
		double rolloff85Acc   = 0.0;
		double bwAcc          = 0.0;  // spectral_bandwidth
		double flatnessAcc    = 0.0;  // spectral_flatness

		PffftSetupGuard fft(FFT_SIZE, PFFFT_REAL);
		if (!fft.p) return;

		// Cutoff bins for band-ratio features at the decimated sample rate.
		const float binHz    = float(outSR) / float(FFT_SIZE);
		const int   lowBinMax  = std::max(1, int(std::floor(LOW_BAND_HZ  / binHz)));
		const int   highBinMin = std::min(HALF_N - 1, int(std::ceil(HIGH_BAND_HZ / binHz)));

		// Prime magPrev from the very first window so hop 0 has a valid
		// predecessor.
		for (int i = 0; i < FFT_SIZE; ++i) win[i] = mono[i] * window[i];
		pffft_transform_ordered(fft.p, win.data(), spec.data(), work.data(), PFFFT_FORWARD);
		computeMagnitudes(spec.data(), magPrev.data(), HALF_N);

		for (int h = 0; h < numHops; ++h) {
			int startIdx  = h * HOP;
			int lastValid = std::min(FFT_SIZE, numFrames - startIdx);
			for (int i = 0; i < lastValid; ++i) win[i] = mono[startIdx + i] * window[i];
			for (int i = lastValid; i < FFT_SIZE; ++i) win[i] = 0.f;

			pffft_transform_ordered(fft.p, win.data(), spec.data(), work.data(), PFFFT_FORWARD);
			computeMagnitudes(spec.data(), magCur.data(), HALF_N);

			onsetSignal[h] = computeSpectralFlux(magCur.data(), magPrev.data(), HALF_N);

			double framePower = 0.0;
			double centroid   = 0.0;
			for (int b = 0; b < HALF_N; ++b) {
				double p = double(magCur[b]) * double(magCur[b]);
				framePower += p;
				centroid   += double(b) * p;
				if (b < lowBinMax)   powerLow  += p;
				if (b >= highBinMin) powerHigh += p;
			}
			powerSum       += framePower;
			centroidBinSum += centroid;

			// Per-frame centroid bin — needed for bandwidth.
			double centroidBinFrame = (framePower > 1e-12) ? centroid / framePower : 0.0;

			// Second pass: spectral_bandwidth + spectral_flatness.
			double bwSq = 0.0, logMagSum = 0.0, linMagSum = 0.0;
			for (int b = 0; b < HALF_N; ++b) {
				double m  = double(magCur[b]);
				double p  = m * m;
				double df = double(b) - centroidBinFrame;
				bwSq      += df * df * p;
				logMagSum  += std::log(m + 1e-12);
				linMagSum  += m;
			}
			// bandwidth: normalised by (HALF_N-1) so it's in [0, ~0.5]
			bwAcc += (framePower > 1e-12)
			       ? std::sqrt(bwSq / framePower) / double(HALF_N - 1)
			       : 0.0;
			// flatness: geometric / arithmetic mean of magnitude, in [0, 1] by AM-GM
			double arithMean = linMagSum / double(HALF_N);
			flatnessAcc += (arithMean > 1e-12)
			             ? std::exp(logMagSum / double(HALF_N)) / arithMean
			             : 0.0;

			// 85 % rolloff. Smallest bin where cumulative mag² ≥ 0.85·frame.
			const double rolloffTarget = 0.85 * framePower;
			double cum = 0.0;
			int    rolloffBin = HALF_N - 1;
			if (framePower > 0.0) {
				for (int b = 0; b < HALF_N; ++b) {
					cum += double(magCur[b]) * double(magCur[b]);
					if (cum >= rolloffTarget) { rolloffBin = b; break; }
				}
			}
			rolloff85Acc += double(rolloffBin) / double(HALF_N - 1);

			// Reuse magCur as the next magPrev via std::swap.
			std::swap(magCur, magPrev);
		}

		// Centroid: (Σ b·p_b) / (Σ p_b), normalised by (HALF_N - 1).
		if (powerSum > 0.0) {
			float centroidMean = float(centroidBinSum / powerSum) / float(HALF_N - 1);
			out[0] = centroidMean;
		}

		// Low-band ratio: total low-band power / total power.
		if (powerSum > 0.0) {
			out[5] = float(powerLow / powerSum);
		}

		// 85 % rolloff: averaged over hops.
		out[1] = float(rolloff85Acc / double(numHops));

		// Onset density: count peaks in the median-filtered onset signal.
		std::vector<float> onsetFiltered(numHops);
		medianFilter3(onsetFiltered.data(), onsetSignal.data(), numHops);
		meanSubtract(onsetFiltered.data(), numHops);

		float maxOnset = 0.f;
		for (float v : onsetFiltered) if (v > maxOnset) maxOnset = v;
		float threshold = 0.5f * maxOnset;
		int   peaks = countPeaks(onsetFiltered.data(), numHops, threshold);
		float peaksPerSec = (numHops > 0)
			? float(peaks) * (float(outSR) / float(HOP)) / float(numHops)
			: 0.f;
		out[4] = peaksPerSec / ONSET_DENSITY_NORM;

		// Spectral flatness: geometric / arithmetic mean of magnitude, averaged over hops.
		out[6] = float(flatnessAcc / double(numHops));

		// Spectral bandwidth: power-weighted std dev of freq, normalised by (HALF_N-1).
		out[7] = float(bwAcc / double(numHops));

		// High-band ratio: energy above HIGH_BAND_HZ / total power.
		if (powerSum > 0.0)
			out[8] = float(powerHigh / powerSum);

		// Mean spectral flux: mean of onsetSignal (log-domain half-rectified flux per hop).
		float fluxSum = 0.f;
		for (int h = 0; h < numHops; ++h) fluxSum += onsetSignal[h];
		out[9] = (fluxSum / float(numHops)) / MEAN_FLUX_NORM;

		// Final clamp to [0, 1].
		for (int i = 0; i < SIREN_TAG_NUM_FEATURES; ++i) {
			if (out[i] < 0.f) out[i] = 0.f;
			else if (out[i] > 1.f) out[i] = 1.f;
		}
	}
};

} // namespace Siren
} // namespace StoermelderPackOne
