#!/usr/bin/env python3
import sys
import os
import json

# Simple generator: walk the examples dir, find .orca files, emit a header with
# an inline function returning vector<pair<string,string>> of (path, content)

def escape_raw(s):
    # We'll wrap each content in a raw string literal with delimiter ORCA
    return s

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('Usage: orca_examples.py <examples-dir>', file=sys.stderr)
        sys.exit(2)
    base = sys.argv[1]
    entries = []
    for root, dirs, files in os.walk(base):
        for f in files:
            if not f.endswith('.orca'):
                continue
            path = os.path.join(root, f)
            rel = os.path.relpath(path, base)
            with open(path, 'r', encoding='utf-8') as fh:
                content = fh.read()
            entries.append((rel.replace('\\', '/'), content))

    entries.sort()

    print('// Auto-generated by orca_examples.py. Do not edit directly.')
    print('#pragma once')
    print('#include <vector>')
    print('#include <string>')
    print('#include <utility>')
    print('inline std::vector<std::pair<std::string,std::string>> getOrcaExamples() {')
    print('    return {')
    for name, content in entries:
        # Use raw string literal with ORCA delimiter
        # Ensure content doesn't contain )ORCA
        if ')ORCA' in content:
            # fallback: escape backslashes and quotes into a normal C string
            esc = content.replace('\\', '\\\\').replace('"', '\\"').replace('\n','\\n')
            print('        {"%s", "%s"},' % (name, esc))
        else:
            print('        {"%s", R"ORCA(%s)ORCA"},' % (name, content.replace('\r','')))
    print('    };')
    print('}')
